force-app/main/default/objects/SFLog__e/SFLog__e.object-meta.xml
<CustomObject>
    <label>SF Log</label>
    <pluralLabel>SF Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/SFLog__e/fields/DataPayload__c.field-meta.xml
<CustomField>
    <fullName>DataPayload__c</fullName>
    <label>Data Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/L.cls
public class L {
    // TODO: fix hardcoded username ...
    public static Boolean d(String message) {
        SFLog__e logEntry = new SFLog__e(
            UserName__c = 'Ruslan Mukhamadeev',
            Message__c = message
        );
        return publishEvent(logEntry);
    }
    
    public static Boolean d(String message, Object payload) {
        SFLog__e logEntry = new SFLog__e(
            UserName__c = 'Ruslan Mukhamadeev',
            Message__c = message,
            DataPayload__c = JSON.serialize(payload)
        );
        return publishEvent(logEntry);
    }
    
    private static Boolean publishEvent(SFLog__e logEntry) {
        Database.SaveResult sr = EventBus.publish(logEntry);
        Boolean res = sr.isSuccess();
		if (!sr.isSuccess()) {
            for(Database.Error err : sr.getErrors()) {
                System.debug('Error returned: ' + err.getStatusCode() + ' - ' + err.getMessage());
            }
		}
        return res;
    }
}